import './game.js';
import './player.js';
import './player/'
import './settings.js';
import './draw.js';
import './functions/';
import './bag/';
import './draw/';
import './controls.js';
import './record.js';
import './tetrisBoard.js';
import './game/'
